services:
  users-service:
    build: ./users-service
    container_name: desafio5-users-service
    networks:
      - gateway-network

  orders-service:
    build: ./orders-service
    container_name: desafio5-orders-service
    networks:
      - gateway-network

  gateway:
    build: ./gateway
    container_name: desafio5-gateway
    depends_on:
      - users-service
      - orders-service
    environment:
      USERS_SERVICE_URL: http://users-service:8080
      ORDERS_SERVICE_URL: http://orders-service:8080
    ports:
      - "8080:8080"
    networks:
      - gateway-network

networks:
  gateway-network:
    driver: bridge

